apiVersion: apps/v1
kind: Deployment
metadata:
  name: btppg-driver
  namespace: default
  labels:
    app: btppg-driver
    version: v2-apikey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btppg-driver
  template:
    metadata:
      labels:
        app: btppg-driver
        version: v2-apikey
    spec:
      containers:
      - name: btppg-driver
        image: fritzgy/btppg-driver:v2-apikey
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: neon-db-secret
        - secretRef:
            name: btppg-api-keys
        env:
        - name: FLASK_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_CONTENT_LENGTH
          value: "52428800"  # 50MB
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: btppg-driver
  namespace: default
  labels:
    app: btppg-driver
spec:
  selector:
    app: btppg-driver
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
