
---
apiVersion: v1
kind: Config
current-context: garden-kyma--c-96dc39d-external
clusters:
- name: garden-kyma--c-96dc39d-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRQXE4SENOSzJCRkloUnBxWUZmM0VSVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TlRBNU1qWXhNalV6TWpWYUZ3MHpOVEE1TWpZeE1qVTBNalZhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUFvaXM3CmU1ZEZnb0prN3Exc3A0THBtWVRxcTk4TzdJMjNzeFVEdmVVMnVESlJrVHFVemNFb04zUk1heFNTNE9SR1V5NzUKOWNWSDRqVnJ0V3FzOC8zSk9EcUxuZGh6L3lEUHBQTkpRRW1OYmkyNnJvTGhWeUFwZFIvS0VGYmJzK2Y0VzdxaAozOEErUzRuTFd0K2hPbXJOenhsOFhvNWNielB2K1dFZEhtR1dQOFBtNFJWazE1UG12QUw3R242RmpiTVhqS2ozClArZ09XVmticXlzWWQ5MTd0VWlmWlI0dHJjazJadm9laDFPTGRoZWxJTHBLOTJNR0ZPa3lzWUg2Vkh5VWhRTWIKZTlHMmIxVkhzTi9pTXlxQ21sKzlNclU1S3hvd2ZtVnlNWXB4UG1ZYWdseDVnWi9sNEx4NW90VllkYUMyOC8vbQoxaFVmOXR2ZVBxT0xROGxCd1g1c0UxbU9YaXFnNnJVQVJUZ2E0L291L1J3TEN3d1ljMnlIYi9sR3E2bElLZUNnClpSWHdoUDY2TThIQ3UwcWQrbnFua1JsclA0Y3BFRU96cTVyTzQwYm8wNTQxWVJ4NVVwVUEwUWlhckNBcDlPdEsKNis4Vk1NTVZlS1BRdERwRlZnUFR5Zy9YS0lGWk9rNEZWYzhXZkxGbEZIU0ZqekhQWXpDYk8rSVRZQld0QWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCVG9OS2RoSlhrWlZwR0FUTmxTU21pcHRXTFZxVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBY0lXNHladjgKc3RwL1NSbHl1dlBoa3hrRFBNZFBDVG4ydkNCdGJLU3NtM25HWVBUa2xlVTRTTFJ4NnF2UGxjZkFRMFlNSW9ZYwpDMHh6MXZrbzlBRmsra0dtTVNOWmE2aGxrSjVxV28xaVhuV1NCUkpPQ2hlZDU2OS9OemJJdk95UE5wZkc3REJSCmhzYnNycWhGNk9icDdLTWI0L0l3QndQQUxxS2lWLzFjM2dkTU9IVlIwNWduOUpteW0weUxqOVNIVk5yTHZTRHoKQmxGdyt2L3JVcUFaT2RmWmg2ZWFHYjFwMHc1QVB4aVZkeTkvSEdZdzVkRDRrelRLRjczSGsrZXNVeTJ2VWZnKwpIK0ZKK0QxMWFrbGFpSFdYVzk4M3dLVFVuYU5QelJaWGlwbVIxc1hpM3VwVFBxNGZ2T1pKTnQxMXpydXBJZDFJCjdETGZWd091aVFHYnBlTmNxbXE3dkFWSHRvYVNtcnZxeXIxWHNielo3UUlLMG1BaGZxSHRDTm82a01DNGxBak4KOW05endCVi8raHVaaHFZRFBjNEtVTTAxNjVFTUVIN3Q2SlU3dk5GZVZsazlSZXdMZXNldndmeDF2MG5veE5QeApOUmltaTkyem42dkwva3ZzeWN0MU5HN1RPbk9EYUFUTXArK2JoaHNPR1pGYTJKcWlnNkN2VlUvOAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-96dc39d.kyma.ondemand.com
contexts:
- name: garden-kyma--c-96dc39d-external
  context:
    cluster: garden-kyma--c-96dc39d-external
    user: garden-kyma--c-96dc39d-external
users:
- name: garden-kyma--c-96dc39d-external
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
